# These are supported funding model platforms

github: nvstly
ko_fi: nvstly
liberapay: nvstly
buy_me_a_coffee: nvstly
thanks_dev: d/gh/nvstlydev/dependencies
custom: https://www.paypal.biz/thetradehub
